# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f6ff2baf91ea5443bd404aa0c36c33521d7c203240e06eefafac849813d1d5118769f6b7cf4822bd0592c9ea654ce6c05476cd28fa2baee2fee68f0186daf3c

test:
  secret_key_base: c58abbb7cfb3dbc8fd3887f46a914aeff2ee09fd85710b2fb03c8a5865de71dd725cf792da397849dee6138d0c41c44b37136d64760d11aa76410b411768b5b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
